# Generated by Django 5.0.1 on 2024-01-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, null=True)),
                ("phone", models.CharField(max_length=200)),
                ("email", models.CharField(max_length=200)),
                ("data_created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
